---
- hosts: common
  vars:

  vars_prompt:
    - name: "username"
      prompt: "Enter your Red Hat username: "
      private: no

    - name: "password" 
      prompt: "Enter your Red Hat password: " 
      private: yes

  remote_user: root
  tasks:
  - name: register system
    redhat_subscription: state=present username={{ username }} password={{ password }} autosubscribe=true

  - name: disable repos
    raw: subscription-manager repos --disable=*

  - name: enable OSE repos
    raw: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.3-rpms"

  - name: install dependencies
    yum: name={{item}} state=present
    with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils 
    - bash-completion

  - name: update all packages, this may take a while.
    yum: name=* state=latest
    register: out

  - name: install OSE installer
    yum: name=atomic-openshift-utils state=present

